module.exports = {
    content: ['./src/pages/LoginPage.js', './src/components/auth/LoginForm.js'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                tertiary: '#000000',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#07006c',
                'on-tertiary-container': '#7073ff',
                'tertiary-fixed': '#e1e0ff',
                'tertiary-fixed-dim': '#c0c1ff',
                'on-tertiary-fixed': '#07006c',
                'on-tertiary-fixed-variant': '#2f2ebe',
                secondary: '#006c49',
                'on-secondary': '#ffffff',
                'secondary-container': '#6cf8bb',
                'on-secondary-container': '#00714d',
                'secondary-fixed': '#6ffbbe',
                'secondary-fixed-dim': '#4edea3',
                'on-secondary-fixed': '#002113',
                'on-secondary-fixed-variant': '#005236',
                primary: '#000000',
                'on-primary': '#ffffff',
                'primary-container': '#131b2e',
                'on-primary-container': '#7c839b',
                'primary-fixed': '#dae2fd',
                'primary-fixed-dim': '#bec6e0',
                'on-primary-fixed': '#131b2e',
                'on-primary-fixed-variant': '#3f465c',
                'inverse-primary': '#bec6e0',
                background: '#f7f9fb',
                'on-background': '#191c1e',
                surface: '#f7f9fb',
                'on-surface': '#191c1e',
                'surface-dim': '#d8dadc',
                'surface-bright': '#f7f9fb',
                'surface-variant': '#e0e3e5',
                'on-surface-variant': '#45464d',
                'surface-tint': '#565e74',
                'inverse-surface': '#2d3133',
                'inverse-on-surface': '#eff1f3',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f2f4f6',
                'surface-container': '#eceef0',
                'surface-container-high': '#e6e8ea',
                'surface-container-highest': '#e0e3e5',
                outline: '#76777d',
                'outline-variant': '#c6c6cd',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'container-max': '1280px',
                base: '4px',
                xs: '8px',
                sm: '16px',
                md: '24px',
                lg: '48px',
                xl: '80px',
                gutter: '24px',
            },
            fontFamily: {
                'body-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'label-xs': ['Geist', 'sans-serif'],
                'label-sm': ['Geist', 'sans-serif'],
                'headline-md': ['Geist', 'sans-serif'],
                'display-lg-mobile': ['Geist', 'sans-serif'],
                'display-lg': ['Geist', 'sans-serif'],
            },
            fontSize: {
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-xs': [
                    '12px',
                    { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
                ],
                'label-sm': [
                    '14px',
                    { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' },
                ],
                'headline-md': [
                    '24px',
                    { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
                ],
                'display-lg-mobile': [
                    '32px',
                    { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
                ],
                'display-lg': [
                    '48px',
                    { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' },
                ],
            },
        },
    },
    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
